# Generated by Django 4.2.7 on 2024-01-26 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_authenticated",
        ),
    ]
