# Generated by Django 4.2.7 on 2024-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0002_remove_user_is_authenticated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="faculty_head",
        ),
        migrations.AlterField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
