# Generated by Django 4.2.7 on 2024-01-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0003_remove_course_faculty_head_alter_user_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("company", models.CharField(max_length=50, null=True)),
                ("instructions", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Payment Option",
                "verbose_name_plural": "Payment Options",
            },
        ),
    ]
