# Generated by Django 4.2.7 on 2024-01-31 14:18

from django.db import migrations, models
import pay_fees.models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0004_paymentmethods"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(default="m-pesa", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="time_stamp",
            field=models.DateTimeField(default=pay_fees.models.default_now, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_code",
            field=models.CharField(
                default=pay_fees.models.code_generate, max_length=50, unique=True
            ),
        ),
    ]
