# Generated by Django 4.2.7 on 2024-01-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0006_transaction_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="user",
        ),
        migrations.AddField(
            model_name="transaction",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="pay_fees.student",
            ),
        ),
    ]
