# Generated by Django 4.2.7 on 2024-02-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0007_remove_transaction_user_transaction_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="checkout_request_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_message",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="merchant_request_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="response_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="response_description",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
