# Generated by Django 4.2.7 on 2024-02-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0008_transaction_checkout_request_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterField(
            model_name="transaction",
            name="checkout_request_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="merchant_request_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
