# Generated by Django 4.2.7 on 2024-03-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0010_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="full_fees",
            field=models.IntegerField(default=45670),
        ),
    ]
