# Generated by Django 4.2.7 on 2024-03-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0011_student_full_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(default="incomplete", max_length=10),
        ),
    ]
