# Generated by Django 4.2.7 on 2024-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0013_staff_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="registration_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
