# Generated by Django 4.2.7 on 2024-03-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_fees", "0015_alter_user_registration_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="fee_balance",
            field=models.IntegerField(default=45670),
        ),
    ]
